// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bktqobrttcqgwvbodcjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdHFvYnJ0dGNxZ3d2Ym9kY2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDk5NzYsImV4cCI6MjA1OTg4NTk3Nn0.mv8bVB3tRQx4wyaxmfIXXdx4ihs2vEk1Aik2xUHuSjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);